# -*- coding: utf-8 -*-
"""Supply_Chain_Simulation.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBlxH7NwkfJk3P9OYEZIgvoWjgn_O1Nf
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# --- 1. DEFINE THE BUSINESS PHYSICS (The Assumptions) ---

# Current State (The "Baseline")
current_radius = 30 # km
daily_revenue_base = 4800000 # Approx ₹176Cr / 365 days (~48 Lakhs/day)

# UNIT ECONOMICS
# 1. Revenue per unit of distance (Linear Growth)
# Assumption: As you expand, you find more villages, so Revenue grows.
revenue_per_km_radius = daily_revenue_base / current_radius

# 2. Transport Cost (Exponential Growth)
# Assumption: Going further costs more fuel AND requires more trucks.
transport_cost_base = 82000 # Approx ₹3Cr / 365 days (~.8 Lakhs/day)
# Cost grows faster than radius because trucks drive empty returns
transport_factor = 1.2

# 3. Spoilage Risk (The "Time" Factor)
# Milk spoils if not chilled within 4 hours. Distance = Time.
def get_spoilage_rate(radius):
    if radius <= 30: return 0.005 # 0.5% loss (Safe zone)
    elif radius <= 45: return 0.02 # 2% loss (Risk increases)
    elif radius <= 60: return 0.05 # 5% loss (High risk)
    else: return 0.10             # 10% loss (Disaster)

# --- 2. RUN THE SIMULATION (Test 10km to 80km) ---
radii = np.arange(10, 85, 5) # Test every 5km step
results = []

for r in radii:
    # A. Scale Revenue (Linear Growth)
    projected_revenue = r * revenue_per_km_radius

    # B. Scale Payout to Women (Fixed 74% Ratio)
    # This is non-negotiable in a cooperative
    payout_cost = projected_revenue * 0.74

    # C. Scale Transport Cost (Non-Linear)
    # Formula: Base Cost * (New Radius / Old Radius) ^ Factor
    projected_transport = transport_cost_base * ((r / current_radius) ** transport_factor)

    # D. Calculate Spoilage Loss
    spoilage_cost = projected_revenue * get_spoilage_rate(r)

    # E. Other Fixed Costs (Plant Electricity, Salaries - 20%)
    fixed_ops_cost = projected_revenue * 0.20

    # F. NET PROFIT CALCULATION
    total_cost = payout_cost + projected_transport + spoilage_cost + fixed_ops_cost
    net_profit = projected_revenue - total_cost

    results.append({
        'Radius (km)': r,
        'Revenue': projected_revenue,
        'Transport': projected_transport,
        'Spoilage': spoilage_cost,
        'Net Profit': net_profit
    })

df_sim = pd.DataFrame(results)

# --- 3. VISUALIZE THE "PROFIT CLIFF" ---
plt.figure(figsize=(12, 7))

# Plot Net Profit
plt.plot(df_sim['Radius (km)'], df_sim['Net Profit'], marker='o', color='green', linewidth=3, label='Daily Net Profit')

# Add the "Break-Even" Line (Zero Profit)
plt.axhline(0, color='red', linestyle='--', linewidth=1, label='Break-Even Point')

# Add the "Current Strategy" Line
plt.axvline(30, color='blue', linestyle='--', label='Current Limit (30km)')

# Find and Plot the Peak
max_profit = df_sim['Net Profit'].max()
optimal_r = df_sim.loc[df_sim['Net Profit'] == max_profit, 'Radius (km)'].values[0]
plt.plot(optimal_r, max_profit, 'r*', markersize=20, label=f'Optimal Radius ({optimal_r}km)')

plt.title('Project C: The "Profit Cliff" Simulation\nWhy Expanding Beyond 30km Destroys Value', fontsize=14, fontweight='bold')
plt.xlabel('Operational Radius (km)', fontsize=12)
plt.ylabel('Daily Net Profit (INR)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('Supply_Chain_Optimization.png')
plt.show()

# --- 4. EXPORT RESULTS TO CSV (New Section) ---
csv_filename = 'MWCD_Supply_Chain_Simulation.csv'
df_sim.to_csv(csv_filename, index=False)

print(f"✅ Optimal Radius Found: {optimal_r} km")
print(f"⚠️ Break-Even Radius (Zero Profit): {df_sim.loc[df_sim['Net Profit'] < 0, 'Radius (km)'].min()} km")
print(f"📂 Simulation Data saved as: '{csv_filename}' (Download this for GitHub!)")